export const vehicleSections = [
  {
    id: "bikes",
    title: "Rent Bike",
    subtitle: "Powerful rides for city and highway travel.",
    route: "/bikes",
    accent: "bg-blue-600",
  },
  {
    id: "cars",
    title: "Rent Car",
    subtitle: "Comfortable, fuel-efficient cars for family and work.",
    route: "/cars",
    accent: "bg-amber-600",
  },
  {
    id: "e-rickshaw",
    title: "Rent E-Rickshaw",
    subtitle: "Affordable electric options for local transport.",
    route: "/e-rickshaw",
    accent: "bg-emerald-600",
  },
];

export const vehiclesBySection = {
  bikes: [
    {
      id: "bike-1",
      title: "Royal Enfield Classic 350",
      type: "Petrol",
      seats: 2,
      transmission: "Manual",
      location: "Downtown Hub",
      rating: 4.8,
      availability: "Available now",
      pricePerDay: 899,
      securityDeposit: 2500,
      features: ["Helmet Included", "100 km/day", "Roadside Assistance"],
    },
    {
      id: "bike-2",
      title: "Bajaj Pulsar NS160",
      type: "Petrol",
      seats: 2,
      transmission: "Manual",
      location: "Railway Station",
      rating: 4.5,
      availability: "3 left",
      pricePerDay: 599,
      securityDeposit: 1800,
      features: ["Mobile Holder", "80 km/day", "Insurance Included"],
    },
    {
      id: "bike-3",
      title: "TVS Apache RTR 200",
      type: "Petrol",
      seats: 2,
      transmission: "Manual",
      location: "Airport Pickup",
      rating: 4.6,
      availability: "5 left",
      pricePerDay: 699,
      securityDeposit: 2200,
      features: ["ABS", "90 km/day", "Free Cancellation"],
    },
  ],
  cars: [
    {
      id: "car-1",
      title: "Maruti Swift",
      type: "Petrol",
      seats: 5,
      transmission: "Manual",
      location: "City Center",
      rating: 4.4,
      availability: "Available now",
      pricePerDay: 1499,
      securityDeposit: 5000,
      features: ["AC", "Unlimited km", "Child Seat on Request"],
    },
    {
      id: "car-2",
      title: "Hyundai Creta",
      type: "Diesel",
      seats: 5,
      transmission: "Automatic",
      location: "Bus Terminal",
      rating: 4.7,
      availability: "2 left",
      pricePerDay: 2399,
      securityDeposit: 8000,
      features: ["SUV", "GPS Included", "Roadside Assistance"],
    },
    {
      id: "car-3",
      title: "Tata Tiago EV",
      type: "Electric",
      seats: 5,
      transmission: "Automatic",
      location: "Tech Park",
      rating: 4.6,
      availability: "4 left",
      pricePerDay: 1999,
      securityDeposit: 6500,
      features: ["Fast Charging", "120 km/day", "Zero Emissions"],
    },
  ],
  "e-rickshaw": [
    {
      id: "rick-1",
      title: "Mahindra Treo",
      type: "Electric",
      seats: 4,
      transmission: "Automatic",
      location: "Market Circle",
      rating: 4.5,
      availability: "Available now",
      pricePerDay: 799,
      securityDeposit: 2000,
      features: ["Battery Included", "60 km/day", "Low Running Cost"],
    },
    {
      id: "rick-2",
      title: "Piaggio Ape E-City",
      type: "Electric",
      seats: 3,
      transmission: "Automatic",
      location: "Old Town",
      rating: 4.3,
      availability: "1 left",
      pricePerDay: 699,
      securityDeposit: 1800,
      features: ["Compact Design", "55 km/day", "Easy Maneuvering"],
    },
    {
      id: "rick-3",
      title: "YC Electric Yatri",
      type: "Electric",
      seats: 4,
      transmission: "Automatic",
      location: "Metro Station",
      rating: 4.2,
      availability: "6 left",
      pricePerDay: 749,
      securityDeposit: 2200,
      features: ["Quick Charging", "65 km/day", "Weather Canopy"],
    },
  ],
};
